package prog2.vista;

import javax.swing.*;

import prog2.adaptador.Adaptador;
import prog2.vista.ComponentsPersonalitzats.*;

import java.awt.*;

public class gestorExemplars extends Finestra {
    private JButton botoMostra;
    private JButton botoAfegir;
    private JButton botoTornar;
    private JPanel PanelExemplars;

    public gestorExemplars(Adaptador adaptador, Finestra pare) {
        super(adaptador, pare);//Preset
        $$$setupUI$$$();//Del Swing UI
        setContentPane(PanelExemplars);//Afegim el contingut
        setTitle("Exemplars");
        botoTornar.addActionListener(e -> tancar());
    }

    private void createUIComponents() {
        PanelExemplars = new Panell();
        botoMostra = new Boto();
        botoAfegir = new Boto();
        botoTornar = new Boto();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        PanelExemplars.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        botoTornar.setIcon(new ImageIcon(getClass().getResource("/prog2/vista/imatges/back.png")));
        botoTornar.setText("Tornar");
        PanelExemplars.add(botoTornar, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        botoAfegir.setIcon(new ImageIcon(getClass().getResource("/prog2/vista/imatges/books.png")));
        botoAfegir.setText("Visualitar-ne");
        PanelExemplars.add(botoAfegir, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        botoMostra.setIcon(new ImageIcon(getClass().getResource("/prog2/vista/imatges/add_book.png")));
        botoMostra.setText("Afegir-ne");
        PanelExemplars.add(botoMostra, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return PanelExemplars;
    }

}
