package prog2.vista;

import prog2.adaptador.Adaptador;

import javax.swing.*;
import java.awt.*;
import prog2.vista.ComponentsPersonalitzats.*;

public class gestorExemplars extends Finestra {
    private JButton botoAfegir;
    private JPanel panelExemplars;
    private JButton botoMostrar;
    private JButton botoTornar;

    public gestorExemplars(Adaptador adaptador, Finestra pare) {
        super();//Preset
        $$$setupUI$$$();//Del Swing UI
        setContentPane(panelExemplars);//Afegim el contingut
        setTitle("Exemplars");

        botoMostrar.addActionListener(e -> {

        });
        botoAfegir.addActionListener(e -> {

        });
        botoTornar.addActionListener(e -> {
            pare.setBloquejar(false);
            dispose();
        });
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panelExemplars.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        botoAfegir.setText("Afegir Exemplar");
        panelExemplars.add(botoAfegir, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        botoMostrar.setText("Mostrar Exemplars");
        panelExemplars.add(botoMostrar, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        botoTornar.setText("Tornar");
        panelExemplars.add(botoTornar, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelExemplars;
    }

    private void createUIComponents() {
        panelExemplars = new Panell();
        botoMostrar = new Boto();
        botoAfegir = new Boto();
        botoTornar = new Boto();
    }
}
